chatbot/urls.py
from django.urls import path
from django.urls import reverse
from . import views
import twitter.views

app_name = 'chatbot'

urlpatterns = [
    path("chatbot/<uuid>/", views.chatbot, name='chatbot_chatbot'),
    path("post/<uuid>/", views.chatbot_process, name='post'),
    path("feed_create/", views.createFeedback, name='create'),
    path("lost_found_create/", views.lostFount, name='lost_found'),
    path("sample/", views.sample, name='sample'),
    path("", views.landing, name='home'),
    path("rule/", views.filter_acct, name='rule'),
    path("data_privacy/", views.data_privacy, name='data_privacy'),

]

twitter/urls.py
from django.urls import path
from . import views
from .views import (intentsDeleteView,sourcesDeleteView,linksDeleteView)
from django.conf import settings
from django.conf.urls.static import static

app_name = 'twitter'

urlpatterns = [
    path("dashboard/", views.twitter_data, name = "chatbot-twitter-data"),
    path("intents/", views.intents, name = "intents"),
    path("uedata/", views.uedata, name='uedata'),
    path("login/",views.accounts_login, name="login"),
    path('logout/', views.logout_view, name="logout"),

    path("intents/<int:pk>/", intentsDeleteView.as_view(), name="updata_delete"),
    path("twitter/<int:pk>/", sourcesDeleteView.as_view(), name="source_delete"),
    path("links/<int:pk>/", linksDeleteView.as_view(), name="links_delete"),


    path("side/", views.side, name="side"),

    
    path("Naive_bayes_Trainer/", views.upload, name="upload_file"),

    path("download_excel/", views.download_excel, name="download_excel"),
    

    path('crud/', views.CrudView.as_view(), name='crud_ajax'),
    path('ajax/crud/create/', views.CreateCrudUser.as_view(), name='crud_ajax_create'),

    path('links/', views.links, name="links"),
    path('ajax/crud/links/', views.linksViesUTwo.as_view(), name='linksViesUTwo'),
    path("classifier_create/", views.trainClass, name='classifier'),
    path("train_Model/", views.train_Model, name='train_model'),
    path("tuning_form/", views.tuningForm, name='tuning'),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chatbot/models.py
from django.db import models
import os, random
import uuid

LOCATION = (
	('Recto Gate', 'RECTO GATE'), 
	('Gastambide Gate', 'GASTAMBIDE GATE')
)

CHOICES = (('L', 'Lost'), ('F', 'Found'))



# Create your models here.

class UserSession(models.Model):
	user_name = models.CharField(max_length=100, verbose_name='User Name')
	gender = models.CharField(max_length=50, verbose_name='Gender')
	user_text = models.TextField(verbose_name='User Input', null=True)
	user_session = models.CharField(max_length=150,verbose_name='User Session', null=True)
	uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
	visits = models.IntegerField(verbose_name="Number of visit", null=True)
	class Meta:
		db_table = "user_session"

	def __str__(self):
		return self.user_name

	def get_abolute_url(self):
		return "/chatbot/%i/" % self.id
	def detail(self):
		return f"Username: {self.user_name}, gender: {self.gender}, Session: {self.user_session}"


#LOST N FOUND TABLE
class LostNFound(models.Model):
	reg_id = models.AutoField(primary_key=True, verbose_name='ID')
	name = models.CharField(max_length=100, verbose_name='Name')
	stud_num = models.CharField(max_length=11, verbose_name = "Student Number", blank=True)
	email = models.EmailField(max_length=50, verbose_name='Email', blank=True)
	contact = models.CharField(max_length=11, verbose_name='Contact Number')
	lost_and_found = models.CharField(max_length=100, verbose_name='Lost & Found' ,choices=CHOICES)
	lostNfound_date = models.DateField(verbose_name='Date')
	lostNfound_time = models.TimeField(verbose_name="Time", blank="True", null="True")

	item = models.CharField(max_length=100,verbose_name='Item')

	item_desc = models.TextField(max_length=500,verbose_name='Item Description')  
	pick_up_loc = models.CharField(max_length=100, verbose_name='Pick-up Location',choices=LOCATION, default='RECTO GATE')


	claimed = models.BooleanField(default=False, verbose_name="Claimed")
	receiver = models.CharField(max_length=100, verbose_name='Received by', blank="True", null="True")
	received_date = models.DateField(verbose_name='Date',  blank="True", null="True")
	received_time = models.TimeField(verbose_name="Time", blank="True", null="True")

	def __str__(self):
		return self.name

	def __unicode__(self):
		return "%s (%s : %s)" % (self.name, self.date_start.strftime('%I:%M %p'), self.lostNfound_time)

class FeedBack(models.Model):
	feedback_name = models.CharField(max_length=100, verbose_name='Name')
	feedback_email = models.CharField(max_length=100, verbose_name='Email')
	feedback_subject = models.CharField(max_length=100, verbose_name='Subject')
	feedback_message = models.TextField(max_length=500,verbose_name='Message')

	def __str__(self):
		return self.feedback_name




chatbot/forms.py
from django import forms
from django.forms import ModelForm
from chatbot.models import *

class UserSessionForm(ModelForm):
	class Meta:
		model = UserSession
		fields = ['user_name', 'gender']


class UserSessionTwoForm(ModelForm):
	class Meta:
		model = UserSession
		fields = ['user_text']

class UserSessionVisit(ModelForm):
	class Meta:
		model = UserSession
		fields = ['visits']

class UserSessionUserS(ModelForm):
	class Meta:
		model = UserSession
		fields = ['user_session']

class FeedbackForm(ModelForm):
	class Meta:
		model = FeedBack
		fields = '__all__'

class LostANDFound(ModelForm):
	class Meta:
		model = LostNFound
		fields = ['name', 'stud_num', 'email', 'contact', 'lost_and_found', 'item', 'item_desc', 'pick_up_loc']
		widgets = {
            'lost_and_found': forms.RadioSelect,
        }

chatbot/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import *

from twitter.models import *
from django.contrib import messages
from .forms import *
from googletrans import Translator
translator = Translator()
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.contrib.sessions.models import Session
from django.contrib.auth.models import User
# =============================================================
# FOR TRAINING-CHATBOT IMPORT
import os
import random
import json
import pickle
import numpy as np
import nltk
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Dense, Activation, Dropout
# from tensorflow.keras.optimizers import SGD
from tensorflow.keras.models import load_model
# ============================================================
#NEW IMPORT
import ftfy
from django.views.decorators.cache import cache_control
# ============================================================
from django.views import View
#FOR TWITTER-API IMPORT
# import tweepy
# import pandas as pd
# Create your views here.
def data_privacy(request):
	return render(request, "chatbot/privacy.html")

def filter_acct(request):
	message = request.GET.getlist('input_text')
	messageTwo = ' '.join([str(elem) for elem in message]) 
	filter_button = messageTwo
	news = Tweets.objects.filter(source=filter_button).values('posts')[:5]
	posts_array = []
	for item in news:
		data = item['posts']
		posts_array.append(data)
	new_post = "\n\n".join(posts_array)
	new_postOne = ftfy.fix_text(str(new_post))
	return HttpResponse(new_postOne)


# ===============================================================
def chatbot_process(request, uuid):
	#INITIALIZATION CHATBOT 
	lemmatizer = WordNetLemmatizer()
	intents = json.loads(open('twitter/intents.json').read())

	words = pickle.load(open('words.pkl', 'rb'))
	classes = pickle.load(open('classes.pkl', 'rb'))

	model = load_model('chatbotmodel.h5')

	# FUNCTION DEFINITION
	def clean_up_sentence(sentence):
	    sentence_words = nltk.word_tokenize(sentence)
	    sentence_words = [lemmatizer.lemmatize(word) for word in sentence_words]
	    return sentence_words

	def bag_of_words(sentence):
	    sentence_words = clean_up_sentence(sentence)
	    bag = [0] * len(words)
	    for w in sentence_words:
	        for i, word in enumerate(words):
	            if word == w:
	                bag[i] = 1
	    return np.array(bag)

	def predict_class(sentence):
	    bow = bag_of_words(sentence)
	    res = model.predict(np.array([bow]))[0]
	    ERROR_THRESHOLD = 0.45
	    results = [[i,r]for i, r in enumerate(res) if r > ERROR_THRESHOLD]

	    results.sort(key = lambda x: x[1], reverse = True)
	    return_list = []
	    for r in results:
	        return_list.append({'intent': classes[r[0]], 'probability': str(r[1])})
	    return return_list

	def get_response(intents_list, intents_json):
		no_answer = ["Sorry, I do not understand", "Sorry, can you elaborate?", "Sorry, can you give more information?"]
		try:
			tag = intents_list[0]['intent']
			list_of_intents = intents_json['intents']
			for i in list_of_intents:
				if i ['tag'] == tag:
					result = random.choice(i['responses'])
					break
			return result
		except:
			result = random.choice(no_answer)
			return result

	# TAKING OF INPUT MESSAGES	
	message = request.GET.getlist('input_text')
	messageTwo = ' '.join([str(elem) for elem in message]) 
	messageTwo = messageTwo.lower()

	translate_words = translator.translate(messageTwo, dest="en")
	result_translate = translate_words.text
	ints = predict_class(str(result_translate))
	response = get_response(ints, intents)
	response = ftfy.fix_text(str(response))

	context = {
	'response':response
	}

	obj = UserSession.objects.get(uuid=uuid)
	# user_v = request.GET.get('user_Visits')
	# print(user_v,"<<++++ VISIT")
	

	# SAVING USER INPUT INTO DATABASE	
	user_text = request.GET.getlist('user_text')
	user_textString = ' '.join([str(elem) for elem in user_text]) 
	translate_NewWords = translator.translate(user_textString, dest="en")
	result_Newtranslate = translate_NewWords.text
	
	
	form = UserSessionTwoForm({'user_text':result_Newtranslate }, instance=obj)
	if form.is_valid():
		form.save()
	return HttpResponse(response)
	

@cache_control(no_cache=True, must_revalidate=True)
def chatbot(request, uuid):
	if request.method=='POST' and 'endSessions' in request.POST:
		user_sessions1 = UserSession.objects.filter(uuid = uuid)
		for user_ses in user_sessions1:
			session = request.session._get_or_create_session_key()
			user_key = UserSession.objects.filter(uuid=uuid).update(user_session=None)
			print("DELETED SESSION KEY")
			return redirect('chatbot:home')

	if request.session.session_key == None:
		return redirect('/')

	user = UserSession.objects.get(uuid=uuid)
	session = request.session._get_or_create_session_key()
	user.user_session = session
	user.save()
	obj = user.uuid
	osy = user.user_name

	user_visits = request.session['visits'] = int(request.session.get('visits',0)) + 1
	form2 = UserSessionVisit({'visits': user_visits}, instance=user)
	if form2.is_valid():
		form2.save()

	Lost = "L"
	Found = "F"
	found_item = LostNFound.objects.filter(lost_and_found = Found)
	lost_item = LostNFound.objects.filter(lost_and_found = Lost)

	lost_fo = LostNFound.objects.all()
	source_t = Source.objects.all()
	form_new = LostANDFound()
	links_model = linksModel.objects.all()
	context={
	'obj':obj, 'user_visits':user_visits, 'links':links_model, 'form_new':form_new,
	'lost_item':lost_item, 'found_item':found_item, 'lost_fo':lost_fo, 'source_t':source_t
	}
	
	return render(request, "chatbot/chatbot.html",context)
	
	
def landing(request):
	if request.method == 'POST':
		user = UserSessionForm(request.POST)
		if user.is_valid():
			user2 = request.POST.get('user_name')
			gender = request.POST.get('gender')
			request.session['user2'] = user2.capitalize()
			request.session['gender'] = gender
			obj = user.save() 
			return redirect('chatbot:chatbot_chatbot', uuid=obj.uuid)
		else:
			messages.info(request, 'Please input')

	try:
		sessionTwo = request.session._get_or_create_session_key()
		user_key = UserSession.objects.get(user_session=sessionTwo)
		if user_key.user_session != None:
			session = request.session._get_or_create_session_key()
			user_key = UserSession.objects.get(user_session=session)
			print(user_key,"<<--")
			return redirect('chatbot:chatbot_chatbot',uuid=user_key.uuid)
	except:
		session = None

		# feedForm = FeedbackForm(request.POST)
		# if feedForm.is_valid():

		# 	messages.info(request, 'Thank you for your feedback :D')
		# 	print("FEEDBACK SAVE")
		# 	feedForm.save()
		# else:
		# 	print("NOT SAVE FEEDBACK CHECK YOUR INPUT")

	return render(request,"chatbot/landing_page.html")

def sample(request):
	if request.method == 'POST':
		user = LostANDFound(request.POST)
		print(user)

		if user.is_valid():
			print("FORM IS VALID !! <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<")
			user.save()
	form_new = LostANDFound()



	context = {
	'form_new':form_new
	}
	return render(request,"chatbot/sample.html",context)


def lostFount(request):
	print("PASOK")
	if request.method == 'POST':
		print("LOST SAVE!!!!")
		name = request.POST['name']
		stud_num = request.POST['stud_num']
		email = request.POST['email']
		contact = request.POST['contact']
		lost_and_found = request.POST['lost_and_found']
		lostNfound_date= request.POST['date']
		lostNfound_time = request.POST['time']
		item = request.POST['item']
		item_desc = request.POST['item_desc']
		pick_up_loc = request.POST['pick_up_loc']
		obj = LostNFound(name=name, stud_num=stud_num, email=email, contact=contact, lost_and_found=lost_and_found,
			item=item, item_desc=item_desc, pick_up_loc=pick_up_loc, lostNfound_time=lostNfound_time, lostNfound_date=lostNfound_date)
		print("LOST & FOUND SAVE!!")
		obj.save()
		source = {'name':obj.name,'lostNfound_date':obj.lostNfound_date,'lostNfound_time':obj.lostNfound_time,'item':obj.item,'item_desc':obj.item_desc, 'lost_and_found':lost_and_found}
		data = {'source': source}
		return JsonResponse(data)
	else:
		print("Check input")
		message = 'No data'
		return HttpResponse(message)


def createFeedback(request):
	if request.method == 'POST':
		feedback_name = request.POST['feedback_name']
		feedback_email = request.POST['feedback_email']
		feedback_subject = request.POST['feedback_subject']
		feedback_message = request.POST['feedback_message']

		feedback_model = FeedBack(feedback_name=feedback_name, feedback_email=feedback_email, feedback_subject=feedback_subject, feedback_message=feedback_message)
		feedback_model.save()
		message = 'Thank you for your feedback ' + feedback_name
		return HttpResponse(message)





chatbot/templates/chatbot/footer.html
<div class="footer">
  <div class="foo"> 
  <p>Copyrights <sapan class="las la-copyright"></sapan>2021 <a href="{% url 'twitter:login' %}" class="url_fo">UEnquire</a> Web Application</p>
 
  </div>
  <div class="new_chat"> <a href="{% url 'chatbot:data_privacy' %}" class="url_fo">Data Privacy Notice</a></div> 
</div>

chatbot/templates/chatbot/landing_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>UEnquire</title>
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;900&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	 <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.3.0/css/line-awesome.min.css"/>
	<link rel="stylesheet" href="{% static 'chatbot/styles/landing.css' %}?{% now "U" %}"">
</head>
<body>
<header>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarTogglerDemo01">
			<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
				<li class="nav-item">
					<a class="nav-link" href="#Features">Features</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#Mission">Mission & Vision</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#FeedBack">FeedBack</a>
				</li>
			</ul>
		</div>
	</nav>
</header>	
<div class="container">
<div class="wave">
    <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
        <path d="M985.66,92.83C906.67,72,823.78,31,743.84,14.19c-82.26-17.34-168.06-16.33-250.45.39-57.84,11.73-114,31.07-172,41.86A600.21,600.21,0,0,1,0,27.35V120H1200V95.8C1132.19,118.92,1055.71,111.31,985.66,92.83Z" class="shape-fill"></path>
    </svg>
</div>


	<section class="home" id="home">
		<div class="content">
			<h2 class="wel">Welcome to UEnquire</h2>
			<div class="des">
			 <p>A University of the East Chatbot that utilizes Twitter using Data Classification. Hybrid system that makes use of Naive Bayes and Neural Network</p>
			 </div>
			<form action="" id="myform" method="POST">
				{% csrf_token %}
				<div class="form-group">

  				<label for="name">What is your nickname?</label>
  				<br>
  				<div class="sample">
  				<input type="text" class="form-control" id="Name" name="user_name"><br>
  				</div>
  				<input type="radio" id="male" name="gender" value="Male">
 				<label for="html">Male</label>
 				<input type="radio" id="female" name="gender" value="Female">
				<label for="css">Female</label><br>	
  				<a href="#" type="submit" id="form_btn" onclick="document.getElementById('myform').submit()" name="submitOne">Submit</a>
  				</div>
  				{% for message in messages %}
  				<script type="text/javascript">
  					window.onload = function(){
  						alert('{{message}}')
  					}
  				</script>
  				{% endfor %}
			</form>
		</div>

		<div class="image">
			<img src="{% static 'chatbot/img/chatbot-marketing.gif' %}" alt="">
		</div>
	</section>
</div>
	<section class="fetures">
		<div class="container">
  <div class="row my-4">
    <div class="col">
        <div class="container-fluid">
        <div class="main_title col-lg-12 mx-auto text-center pb-5" ><p id="Features">Features</p></div>
          <div class="row">
          	<div class="col-sm d-flex my_cards" >
          		<div class="card text-center">
          			<div class="card-header">
          				1
          			</div>
          			<div class="card card-body flex-fill">
          				
          				<p class="card-text">UEnquire use Twitter to gain access to UE related tweets which are used to enforce the validity of the chatbot.</p>
          			<!-- 	<a href="#" class="btn btn-primary">Go somewhere</a> -->
          			</div>
          		</div>
          	</div>
            
          	<div class="col-sm d-flex my_cards">
          		<div class="card text-center">
          			<div class="card-header">
          				2
          			</div>
          			<div class="card card-body flex-fill">
          				
          				<p class="card-text">Admin's management dashboard are used to manage the Chatbot and Classifier models as well as operate database objects and functions  </p>
          			<!-- 	<a href="#" class="btn btn-primary">Go somewhere</a> -->
          			</div>
          		</div>
          	</div>
            
          	<div class="col-sm d-flex my_cards">
          		<div class="card text-center">
          			<div class="card-header">
          				3
          			</div>
          			<div class="card card-body flex-fill">
          				
          				<p class="card-text">Chatbot can change and adapt through Training Datasets, can learn and eat new data 
with indirect aid from the system classifier who is also a trainable model. </p>
          				<!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
          			</div>
          		</div>
          	</div>
          	<div class="col-sm d-flex my_cards">
          		<div class="card text-center">
          			<div class="card-header">
          				4
          			</div>
          			<div class="card card-body flex-fill">
          				<p class="card-text">Model description for both Chatbot and Classifier are displayed in the dashboard </p>
          				<!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
          			</div>
          		</div>
          	</div>
            
          </div>
          
        </div>

    </div>
  </div>
</div>
	</section>

	<section class="mission_vision" id="mis_vis_id">
		<div class="container">
			<div class="overlay2"></div>
			<div class="main_title_two col-lg-12 mx-auto text-center pb-5" ><p id="Mission">Mission & Vision</p></div>
			<div class="row">
				
				<div class="col-md-6">
					<div class="vision_title">Mission</div>
					<div class="mission_body">
						<p class="p_1">
							 To develop a system that assist the University of the East's inquiry process and create a chatbot with 
adaptive capabilities. 
						</p>
					</div>
				</div>
				<div class="col-md-6">
					<div class="vision_title">Vision</div>
					<div class="vision_body">
						<p class="p_1">
							Create a system which stems many researches from various fields and serve as a pioneer tool to these 
future researchers. 

						</p>
					</div>
				</div>
			</div>
			
		</div>
	</section>

	<section class="feedback">
	<!-- 	<div class="back_feed"></div> -->
		<div class="container">
			<div class="main_title_3 col-lg-12 mx-auto text-center pb-5" ><p id="FeedBack">FeedBack Form</p></div>
			<div class="feed_main">
				<div class="feed_head">
					<h2>Send us your feedback!</h2>
					<p>Do you have a suggestion or found some bug?
						let us known in the field bellow
					</p>
					<!-- <p>let us known in the field bellow</p> -->
				</div>
				
				<hr>
<br>
			<form action="" method="POST" id="myForm_feed">
				{% csrf_token %}
				<div class="form-row">
					<div class="form-group col-md-4">
						<label for="inputAddress">Name:</label>
						<input type="text" class="form-control" name="feedback_name" id="feedback_name" placeholder="Enter name" required>
					</div>
					<div class="form-group col-md-8">
						<label for="inputEmail4">Email:</label>
						<input type="email" class="form-control" name="feedback_email" id="feedback_email" placeholder="Enter email" required>
					</div>

				</div>
				<div class="form-group">
					<label for="inputAddress2">Subject:</label>
					<input type="text" class="form-control" name="feedback_subject" id="feedback_subject" placeholder="Enter subject" required>
				</div>
				<div class="form-group">
					<label for="exampleFormControlTextarea1">Message:</label>
					<textarea class="form-control" name="feedback_message" id="feedback_message" rows="3" placeholder="Enter message" required></textarea>
				</div>
				<button type="submit" name="feedbak_form" class="btn btn-primary">Submit</button>


			</form>

			</div>
			<div class="but_wave">
				<div class="new_wave n_wave1"></div>
				<div class="new_wave n_wave2"></div>
				<div class="new_wave n_wave3"></div>
				<div class="new_wave n_wave4"></div>
			</div>
		</div>
	</section>
	{% include 'chatbot/footer.html' %}



<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>


<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.2/dist/sweetalert2.all.min.js"></script>



<script type="text/javascript">
	$("#myForm_feed").on("submit", function(e){
	e.preventDefault();
		var url = '{% url "chatbot:create" %}'
		$.ajax({
			type:'POST',
			url:url,
			data:{
				feedback_name:$('#feedback_name').val(),
				feedback_email:$('#feedback_email').val(),
				feedback_subject:$('#feedback_subject').val(),
				feedback_message:$('#feedback_message').val(),
				csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
			},
			success:function(data){
				Swal.fire({
					position: 'center',
					icon: 'success',
					title: data,
					showConfirmButton: false,
					timer: 1600
				})
				$('#feedback_name').val('');
				$('#feedback_email').val('');
				$('#feedback_subject').val('');
				$('#feedback_message').val('');
			}
		});
	});


	// const buttons = document.querySelectorAll('a');
	// buttons.forEach(btn =>{
	// 	btn.addEventListener('click', function(e){

	// 		let x = e.clientX - e.target.offsetLeft;
	// 		let y = e.clientY - e.target.offsetTop;

	// 		let ripples = document.createElement('span');
	// 		ripples.style.left = x + 'px';
	// 		ripples.style.top = y + 'px';
	// 		this.appendChild(ripples);

	// 		setTimeout(()=>{
	// 			ripples.remove()
	// 		},1000);
	// 	})
	// })


// function setCookie(name,value,days) {
//     var expires = "";
//     if (days) {
//         var date = new Date();
//         date.setTime(date.getTime() + (days*24*60*60*1000));
//         expires = "; expires=" + date.toUTCString();
//     }
//     document.cookie = name + "=" + (value || "")  + expires + "; path=/";
// }
// function getCookie(name) {
//     var nameEQ = name + "=";
//     var ca = document.cookie.split(';');
//     for(var i=0;i < ca.length;i++) {
//         var c = ca[i];
//         while (c.charAt(0)==' ') c = c.substring(1,c.length);
//         if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
//     }
//     return null;
// }
// function eraseCookie(name) {   
//     document.cookie = name+'=; Max-Age=-99999999;';  
// }

</script>

</body>
</html>

chatbot/templates/chatbot/privacy.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Data Privacy</title>

	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">


	<link rel="stylesheet" href="{% static 'chatbot/styles/landing.css' %}?{% now "U" %}"">


</head>
<body class="body_da">
	<header>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarTogglerDemo01">
			<ul class="navbar-nav mr-auto mt-2 mt-lg-0">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'chatbot:home' %}">Back</a>
				</li>
			</ul>
		</div>
	</nav>
</header>
	<div class="container">
		<div class="main_privacy">

			
			<div class="header_pri">
				<div class="cellcenterparent">
					<div class="cellcentercontent">
						<h1 id="Head_pri">UEnquire PRIVACY STATEMENT</h1> 
					</div>
					
				</div>
			</div>
			<div class="privacy_con">
			<p>Under the Data Privacy Act of 2012 (RA 10173), UEnquire will collect this information for the assessment, improvement and evaluation of the training model to be used in the Naive Bayes and Neural Network algorithm. Rest assured that the data or information you share with us are safe and will be treated with the utmost confidentiality.</p>
			</div>
		</div>
	</div>
</body>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</html>