chatbot/urls.py
from django.urls import path
from django.urls import reverse
from . import views
import twitter.views

app_name = 'chatbot'

urlpatterns = [
    path("chatbot/<uuid>/", views.chatbot, name='chatbot_chatbot'),
    path("post/<uuid>/", views.chatbot_process, name='post'),
    path("feed_create/", views.createFeedback, name='create'),
    path("lost_found_create/", views.lostFount, name='lost_found'),
    path("sample/", views.sample, name='sample'),
    path("", views.landing, name='home'),
    path("rule/", views.filter_acct, name='rule'),
    path("data_privacy/", views.data_privacy, name='data_privacy'),

]

twitter/urls.py
from django.urls import path
from . import views
from .views import (intentsDeleteView,sourcesDeleteView,linksDeleteView)
from django.conf import settings
from django.conf.urls.static import static

app_name = 'twitter'

urlpatterns = [
    path("dashboard/", views.twitter_data, name = "chatbot-twitter-data"),
    path("intents/", views.intents, name = "intents"),
    path("uedata/", views.uedata, name='uedata'),
    path("login/",views.accounts_login, name="login"),
    path('logout/', views.logout_view, name="logout"),

    path("intents/<int:pk>/", intentsDeleteView.as_view(), name="updata_delete"),
    path("twitter/<int:pk>/", sourcesDeleteView.as_view(), name="source_delete"),
    path("links/<int:pk>/", linksDeleteView.as_view(), name="links_delete"),


    path("side/", views.side, name="side"),

    
    path("Naive_bayes_Trainer/", views.upload, name="upload_file"),

    path("download_excel/", views.download_excel, name="download_excel"),
    

    path('crud/', views.CrudView.as_view(), name='crud_ajax'),
    path('ajax/crud/create/', views.CreateCrudUser.as_view(), name='crud_ajax_create'),

    path('links/', views.links, name="links"),
    path('ajax/crud/links/', views.linksViesUTwo.as_view(), name='linksViesUTwo'),
    path("classifier_create/", views.trainClass, name='classifier'),
    path("train_Model/", views.train_Model, name='train_model'),
    path("tuning_form/", views.tuningForm, name='tuning'),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter/forms.py
from django import forms
from django.forms import ModelForm
from twitter.models import *

from django.contrib.auth import authenticate
from django.contrib.auth import views
import os


from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.utils.translation import gettext_lazy as _

from django.core.exceptions import ValidationError

class ClassifierSettingsForm(ModelForm):
	class Meta:
		model = ClassifierSettings
		fields = ['average']

class linksForm(ModelForm):
	class Meta:
		model = linksModel
		fields = ['link_name', 'links']

class anaUploadForm(forms.FileField):
	filename = models.CharField(max_length=200)
	json_file = forms.FileField(widget=forms.FileInput(attrs={'accept':'application/pdf'}),)
	class Meta:
		model = analyticsUpload
		fields = '__all__'

class IntentsForm(ModelForm):
	class Meta:
		model = Intents
		fields = ["tag", "pattern", "response", "context", "context_set"]

class SourceForm(ModelForm):
	class Meta:
		model = Source
		fields = ['source_acct']


#ACCOUNT AUTHENTICATION
class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")

class RegistrationForm(UserCreationForm):
	email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')
	class Meta:
		model = Account
		fields = ('username', 'email', 'password1', 'password2',)

	def clean_email(self):

		email = self.cleaned_data['email'].lower()
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Exception as e:
			return email
		raise forms.ValidationError('Email "%s" is already in use.' % account)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except  Exception as e:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)

twitter/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
import pandas as pd
from django.contrib.auth.models import User
import os
import random
import json

from tensorflow.keras.models import load_model
# ============================================================
import subprocess
from .models import *
from .forms import *
import re
# ============================================================
from twitter.forms import SourceForm, RegistrationForm, AccountAuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password , check_password
from django.contrib import messages
from twitter.decorators import unauthenticated_user, allowed_users
# ============================================================
from django.views import View
from django.template import loader
# ============================================================
# from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import ListView

from django.core.files.storage import FileSystemStorage

# ========================================================================================

class CrudView(ListView):
    model = Source
    template_name = 'twitter/Crud.html'
    context_object_name = 'source'

class CreateCrudUser(View):
    def  get(self, request):
    	name_source = request.GET.get('source_acct', None)
    	print(name_source)
    	obj = Source.objects.create(source_acct = name_source)
    	source = {'twitter_id':obj.twitter_id,'source_acct':obj.source_acct}
    	data = {'source': source}
    	return JsonResponse(data)

class linksViesUTwo(View):
    def  get(self, request):
    	link_name = request.GET.get('link_name', None)
    	links = request.GET.get('links', None)
    	obj = linksModel.objects.create(link_name = link_name, links = links)
    	source = {'link_id':obj.link_id,'link_name':link_name, 'links':obj.links}
    	data = {'source': source}
    	return JsonResponse(data)
# ========================================================================================
# UPLOAD DATASET FOR NAIVE BAYES 
from twitter.backend import training_classifier as classifier
from twitter.backend import uploads 
@login_required(login_url='twitter:login')
def upload(request):
	files = analyticsUpload.objects.all()
	uploadsF = ClassifierSettingsForm()
	context = {
		'files': files,
		'classifier_settings': ClassifierSettings.objects.all().last(),
		'model_desc': ClassifierModels.objects.all().last(),
		'uploadsF':uploadsF
	}
	if request.method == 'POST' and 'upload_dataset' in request.POST:
		request = uploads.naive_bayes_upload(request, analyticsUpload)

	# if request.method == 'POST' and 'upload_class' in request.POST:
	# 	upload_classify = request.FILES['upload_input']
		# upload_file = FileSystemStorage() #GINAGAWA NYANG FileSystemStorage PAG NAG UPLOAD KA ULIT NG PAREHAS NA FILE NAME PAPALITAN NYA YUN NG BAGONG FILE NAME
		# upload_file.save(upload_classify.name, upload_classify)
	
	
	# if request.method == 'POST' and 'upload_toClassify' in request.POST:
	# 	# TAKE NOTE: FIND A WAY TO SAVE AN INSTANCE OF A CLASS
	# 	pass

	return render(request, "twitter/upload_file/analytics_upload.html", context)

@login_required(login_url='twitter:login')
def trainClass(request):
	print("======================NEW CLSS =======================")
	if request.method == 'POST':
		test_size = request.POST['newTest']
		random_state = request.POST['random_state']
		average = request.POST['average']
		obj = ClassifierSettings(test_size=test_size, rand_state=random_state, average=average)
		obj.save()
		source = {'test_size':obj.test_size, 'rand_state':obj.rand_state, 'average':obj.average}
		data = {'source': source}
		return JsonResponse(data)
		
@login_required(login_url='twitter:login')
def train_Model(request):
	print("======================NEW TRAIN=======================")
	data_two = {}
	if request.method == 'POST':
		print("<<<<<<<<<<<<<<<<<< 111")
		file = request.POST['sub_train']
		file_obj = analyticsUpload.objects.get(name=file)
		print("<<<<<<<<<<<<<<<<<< 1222")
		if ClassifierSettings.objects.all().count() != 0:
			settings = ClassifierSettings.objects.all().last()
			print("<<<<<<<<<<<<<<<<<< 333")
			classifier_model, scores, vectorizer = classifier.naive_bayes(file_obj.file, settings.test_size, settings.rand_state, settings.average)
			print("<<<<<<<<<<<<<<<<<< 444")
			data_scores = pd.DataFrame([scores])
			print("<<<<<<<<<<<<<<<<<< 5555")
			d = data_scores.to_json(orient='records')
			data = json.loads(d)

			allScore = []
			for score in data:
				allScore.append((score['correct'], score['incorrect'], score['accuracy'],
					score['recall'], score['precision'], score['f1_score']))

			correct = None
			incorrect = None
			accuracy = None
			recall = None
			precision = None
			f1_score = None

			for i in allScore:
				correct = str(i[0])
				incorrect = str(i[1])
				accuracy = str(i[2])
				recall = str(i[3])
				precision = str(i[4])
				f1_score = str(i[5])

				sourceTwo = {'correct':correct, 'incorrect':incorrect, 'accuracy':accuracy, 'recall':recall,
				'precision':precision, 'f1_score':f1_score}

				print("TRAINING COMPLETE")
				message = "TRAINING COMPLETE"
				data_two = {'sourceTwo':sourceTwo, 'message':message}
			

			entry = ClassifierModels(
				correct=correct, incorrect=incorrect, accuracy=accuracy,
				recall=recall, precision=precision, f1_score=f1_score)
			entry.save()

		print(type(data_two))		
		return JsonResponse(data_two)

# ========================================================================================
# DOWNLOAD TWEETS EXCEL
from twitter.backend import download_file as dl
def download_excel(request):
	request = dl.excel_dl(Tweets)
	return request
# ========================================================================================
# TWITTER MAIN TABLE 
from twitter.backend import tw_backend as tw
@login_required(login_url='twitter:login')
def twitter_data(request):
	api = tw.open_acct()
	num_post = 1
	# Admin Inputs
	if request.method == 'POST' and 'num_posts' in request.POST:
		num_post = int(request.POST.get('number'))

	if request.method == 'POST' and 'sour_sub' in request.POST:
		sources = SourceForm(request.POST)
		# obj = sources.source_acct
		if sources.is_valid():
			sources.save()
		else:
			print("Invalid")
	if Source.objects.all().count() == 0:
		accounts = []
	else:
		accounts = Source.objects.all()
		accounts = tw.output(accounts, api, num_post)		
	# CONTEXT
	tweets = Tweets.objects.all()
	context = {'tweets': tweets, 'source_list': accounts}
	return render(request, "twitter/analytics.html", context)
# ========================================================================================
# INTENTS MAIN TABLE
from twitter.backend import training_chatbot as train_bot
# from twitter.backend import intents_backend as intent 
@login_required(login_url='twitter:login')
def intents(request):
	json_file = "twitter/intents.json"
	with open (json_file, "r") as file:
		data = json.load(file)
	form = Intents.objects.all()

	try:
		form[0]
	except IndexError:
		for item in data["intents"]:
			Intents(
				tag= item["tag"], pattern= item["patterns"], response= item["responses"], 
				context= item["context"], context_set= item["context_set"]
				).save()

	# TRAINING OF CHATBOT MODEL 
	if request.method == 'POST' and 'train_chatbot' in request.POST:
		train_bot.chatbot_training(request, ChatbotTuning)

	
	elif request.method == 'POST':
		print('asdadadadadadada')	
		def convert(string):
			clean = []
			if len(string) == 0:
				return []
			li = re.split(r',(?=")', string)
			for word in li:
				chars = list(word)
				if len(chars)!= 0:
					chars.pop(0)
					chars.pop()
				word = "".join(chars)
				clean.append(word)
			return clean
		
		tag = request.POST.get('tag')
		patterns = convert(request.POST.get('patterns'))
		responses = convert(request.POST.get('responses'))
		context = request.POST.get('context')
		context_set = convert(request.POST.get('context_set'))

		print("++++++++++++==")		
		form = Intents(tag=tag, pattern=patterns, response=responses, context=context, context_set=context_set)
		form.save()
		new_obj = {"tag": tag, "patterns": patterns, "responses": responses, "context": context, "context_set": context_set}
		

		data["intents"].append(new_obj) 
		with open("twitter/intents.json", 'w') as data_file:
			json.dump(data, data_file, indent=4)
		return JsonResponse({'new_form': new_obj})

	tuner = ''
	if  ChatbotTuning.objects.all().count() != 0:
		tuner = ChatbotTuning.objects.last()
	
	dictionary = {'intents': form, 'tuner': tuner}
	# ====================================================================
	return render(request, "twitter/chatbot_intents.html", dictionary)

from twitter.backend import training_chatbot as train_bot
def tuningForm(request):
	print("======================TRAINING TUNING=======================")
	if request.method == 'POST':
		train_bot.chatbot_training(request, ChatbotTuning)
		epoch = request.POST['id_input_epoch']
		rate = request.POST['id_input_lr']
		batch = request.POST['id_input_bs']
		obj = ChatbotTuning(epoch=epoch, rate=rate, batch=batch)
		obj.save()
		source = {'epoch':obj.epoch, 'rate':obj.rate, 'batch':obj.batch}
		data = {'source': source}
		return JsonResponse(data)


class intentsDeleteView(View):
	def get(self,request, pk, *args, **kwargs):
		if request.is_ajax():
			print("<<<<<=================DELETE========================")
			tag = Intents.objects.get(pk=pk)
			tag_name = str(tag.tag)
			tag.delete()

twitter/templates/twitter/sidebar_and_head/sidebar.html
{% url 'twitter:chatbot-twitter-data' as  twitter_data %}
{% url 'twitter:intents' as  intents %}
{% if request.user.is_authenticated and request.user and request.user.is_staff == False  %}
<style>
  .navbar-default{
     background-color: #FFF;
     margin-left: 0px;
  }
  .mnb {
    background-color: #ba0000;
    color: #fff;
}

</style>
{% endif %} 
<nav class="mnb navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    
    <div class="navbar-header" id="try_one">
     
      <button type="button" id="tog_id" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <i class="ic fa fa-bars"></i>
      </button>
      {% if request.user.is_authenticated and request.user and request.user.is_staff == False  %}
      <div style="padding: 15px 0;">
         <a href="#" id="msbo"></i></a>
      </div>
      {% endif %} 
       {% if request.user.is_authenticated and request.user.is_staff %}
      <div style="padding: 15px 0;">
         <a href="#" id="msbo"><i class="ic fa fa-bars"></i></a>
      </div>
      {% endif %} 
    </div>
    
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" id="user_name">
             {% if request.user.is_authenticated %}
             Hi, {{request.user}}
             {% endif %}
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{% url 'twitter:logout' %}">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>


{% if request.user.is_authenticated and request.user.is_staff %}
<!--msb: main sidebar-->
<div class="msb" id="msb">
    <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <div class="brand-wrapper">
          <!-- Brand -->
          <div class="brand-name-wrapper">
            <a class="navbar-brand" href="">
             UEnquire Admin
            </a>
          </div>

        </div>

      </div>

      <!-- Main Menu -->
      <div class="side-menu-container">
        <ul class="nav navbar-nav">

            <li class="panel panel-default" id="dropdown">
            <a data-toggle="collapse" href="#dropdown-lvl22" class="{% if request.path == twitter_data %} active {% endif %}">
              <i class="fa fa-list-alt"></i> Twitter Data
              <span class="caret"></span>
            </a>
            <!-- Dropdown level 1 -->
            <div id="dropdown-lvl22" class="panel-collapse collapse">
              <div class="panel-body">
                <ul class="nav navbar-nav">
                  <li><a href="{% url 'twitter:chatbot-twitter-data' %}" class="{% if request.path == twitter_data %} active {% endif %}">Twitter Data</a></li>
                  <li><a href="{% url 'twitter:upload_file' %}">Upload file</a></li>
                  <!-- Dropdown level 2 -->
                </ul>
              </div>
            </div>
          </li>


          <li ><a href="{% url 'twitter:intents' %}" class="{% if request.path == intents %} active {% endif %}"><i class="fa fa-file-text-o"></i>Intents Json</a></li>



        <!--   <li><a href=""><i class="fa fa-heart"></i> Extras</a></li> -->

  <!-- 
          <li class="panel panel-default" id="dropdown">
            <a data-toggle="collapse" href="#dropdown-lvl1">
              <i class="fa fa-diamond"></i> Apps
              <span class="caret"></span>
            </a>

            <div id="dropdown-lvl1" class="panel-collapse collapse">
              <div class="panel-body">
                <ul class="nav navbar-nav">
                  <li><a href="">Mail</a></li>
                  <li><a href="">Calendar</a></li>
                  <li><a href="">Ecommerce</a></li>
                  <li><a href="">User</a></li>
                  <li><a href="">Social</a></li>

                  
                  <li class="panel panel-default" id="dropdown">
                    <a data-toggle="collapse" href="#dropdown-lvl2">
                      <i class="glyphicon glyphicon-off"></i> Sub Level <span class="caret"></span>
                    </a>
                    <div id="dropdown-lvl2" class="panel-collapse collapse">
                      <div class="panel-body">
                        <ul class="nav navbar-nav">
                          <li><a href="">Link</a></li>
                          <li><a href="">Link</a></li>
                          <li><a href="">Link</a></li>
                        </ul>
                      </div>
                    </div>
                  </li>
                </ul>
              </div>
            </div>
          </li> -->

          <li><a href="{% url 'twitter:links' %}"><span class="glyphicon glyphicon-signal"></span>Links</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>  
</div>

<!-- {% if request.user.is_authenticated and request.user and request.user.is_staff == False  %}
<script>

</script>
{% endif %}  -->
{% endif %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cpwebassets.codepen.io/assets/common/stopExecutionOnTimeout-1b93190375e9ccc259df3a57c1abc0e64599724ae30d7ea4c6877eb615f89387.js"></script>



<script type="text/javascript">
   setTimeout(document.getElementById('try_one').click(),2000);
  (function(){
  $('#msbo').on('click', function(){
   $('body').toggleClass('msb-x');

//  var countdown = 10;
  //  const interval = setInterval(() => {
  //   countdown = --countdown <= 0 ? 10 : countdown;
  //   console.log(countdown,"<<")
  //   if (countdown == 1) {
  //     $('body').toggleClass('msb-x');
  //     clearInterval(interval);
  //   }
  // }, 2000)

 });
}());

var iteration = true;
var time = new Date();
var delay = 5000; // 5 secondes

while(iteration) {
  if(time.getTime() + 5000 < new Date().getTime()) {
   iteration = false;
 }
}

document.getElementById('msbo').click();


  // var countdown = 10;
  // const interval = setInterval(() => {
  //   countdown = --countdown <= 0 ? 10 : countdown;
  //   console.log(countdown,"<<")
  //   if (countdown == 1) {
  //     $('body').toggleClass('msb-x');
  //     clearInterval(interval);
  //   }
  // }, 1000)

</script>


{% endblock scripts %}