chatbot/urls.py
from django.urls import path
from django.urls import reverse
from . import views
import twitter.views

app_name = 'chatbot'

urlpatterns = [
    path("chatbot/<uuid>/", views.chatbot, name='chatbot_chatbot'),
    path("post/<uuid>/", views.chatbot_process, name='post'),
    path("feed_create/", views.createFeedback, name='create'),
    path("lost_found_create/", views.lostFount, name='lost_found'),
    path("sample/", views.sample, name='sample'),
    path("", views.landing, name='home'),
    path("rule/", views.filter_acct, name='rule'),
    path("data_privacy/", views.data_privacy, name='data_privacy'),

]

twitter/urls.py
from django.urls import path
from . import views
from .views import (intentsDeleteView,sourcesDeleteView,linksDeleteView)
from django.conf import settings
from django.conf.urls.static import static

app_name = 'twitter'

urlpatterns = [
    path("dashboard/", views.twitter_data, name = "chatbot-twitter-data"),
    path("intents/", views.intents, name = "intents"),
    path("uedata/", views.uedata, name='uedata'),
    path("login/",views.accounts_login, name="login"),
    path('logout/', views.logout_view, name="logout"),

    path("intents/<int:pk>/", intentsDeleteView.as_view(), name="updata_delete"),
    path("twitter/<int:pk>/", sourcesDeleteView.as_view(), name="source_delete"),
    path("links/<int:pk>/", linksDeleteView.as_view(), name="links_delete"),


    path("side/", views.side, name="side"),

    
    path("Naive_bayes_Trainer/", views.upload, name="upload_file"),

    path("download_excel/", views.download_excel, name="download_excel"),
    

    path('crud/', views.CrudView.as_view(), name='crud_ajax'),
    path('ajax/crud/create/', views.CreateCrudUser.as_view(), name='crud_ajax_create'),

    path('links/', views.links, name="links"),
    path('ajax/crud/links/', views.linksViesUTwo.as_view(), name='linksViesUTwo'),
    path("classifier_create/", views.trainClass, name='classifier'),
    path("train_Model/", views.train_Model, name='train_model'),
    path("tuning_form/", views.tuningForm, name='tuning'),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter/forms.py
from django import forms
from django.forms import ModelForm
from twitter.models import *

from django.contrib.auth import authenticate
from django.contrib.auth import views
import os


from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.utils.translation import gettext_lazy as _

from django.core.exceptions import ValidationError

class ClassifierSettingsForm(ModelForm):
	class Meta:
		model = ClassifierSettings
		fields = ['average']

class linksForm(ModelForm):
	class Meta:
		model = linksModel
		fields = ['link_name', 'links']

class anaUploadForm(forms.FileField):
	filename = models.CharField(max_length=200)
	json_file = forms.FileField(widget=forms.FileInput(attrs={'accept':'application/pdf'}),)
	class Meta:
		model = analyticsUpload
		fields = '__all__'

class IntentsForm(ModelForm):
	class Meta:
		model = Intents
		fields = ["tag", "pattern", "response", "context", "context_set"]

class SourceForm(ModelForm):
	class Meta:
		model = Source
		fields = ['source_acct']


#ACCOUNT AUTHENTICATION
class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")

class RegistrationForm(UserCreationForm):
	email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')
	class Meta:
		model = Account
		fields = ('username', 'email', 'password1', 'password2',)

	def clean_email(self):

		email = self.cleaned_data['email'].lower()
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Exception as e:
			return email
		raise forms.ValidationError('Email "%s" is already in use.' % account)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except  Exception as e:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)

twitter/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
import pandas as pd
from django.contrib.auth.models import User
import os
import random
import json

from tensorflow.keras.models import load_model
# ============================================================
import subprocess
from .models import *
from .forms import *
import re
# ============================================================
from twitter.forms import SourceForm, RegistrationForm, AccountAuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password , check_password
from django.contrib import messages
from twitter.decorators import unauthenticated_user, allowed_users
# ============================================================
from django.views import View
from django.template import loader
# ============================================================
# from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import ListView

from django.core.files.storage import FileSystemStorage

# ========================================================================================

class CrudView(ListView):
    model = Source
    template_name = 'twitter/Crud.html'
    context_object_name = 'source'

class CreateCrudUser(View):
    def  get(self, request):
    	name_source = request.GET.get('source_acct', None)
    	print(name_source)
    	obj = Source.objects.create(source_acct = name_source)
    	source = {'twitter_id':obj.twitter_id,'source_acct':obj.source_acct}
    	data = {'source': source}
    	return JsonResponse(data)

class linksViesUTwo(View):
    def  get(self, request):
    	link_name = request.GET.get('link_name', None)
    	links = request.GET.get('links', None)
    	obj = linksModel.objects.create(link_name = link_name, links = links)
    	source = {'link_id':obj.link_id,'link_name':link_name, 'links':obj.links}
    	data = {'source': source}
    	return JsonResponse(data)
# ========================================================================================
# UPLOAD DATASET FOR NAIVE BAYES 
from twitter.backend import training_classifier as classifier
from twitter.backend import uploads 
@login_required(login_url='twitter:login')
def upload(request):
	files = analyticsUpload.objects.all()
	uploadsF = ClassifierSettingsForm()
	context = {
		'files': files,
		'classifier_settings': ClassifierSettings.objects.all().last(),
		'model_desc': ClassifierModels.objects.all().last(),
		'uploadsF':uploadsF
	}
	if request.method == 'POST' and 'upload_dataset' in request.POST:
		request = uploads.naive_bayes_upload(request, analyticsUpload)

	# if request.method == 'POST' and 'upload_class' in request.POST:
	# 	upload_classify = request.FILES['upload_input']
		# upload_file = FileSystemStorage() #GINAGAWA NYANG FileSystemStorage PAG NAG UPLOAD KA ULIT NG PAREHAS NA FILE NAME PAPALITAN NYA YUN NG BAGONG FILE NAME
		# upload_file.save(upload_classify.name, upload_classify)
	
	
	# if request.method == 'POST' and 'upload_toClassify' in request.POST:
	# 	# TAKE NOTE: FIND A WAY TO SAVE AN INSTANCE OF A CLASS
	# 	pass

	return render(request, "twitter/upload_file/analytics_upload.html", context)

@login_required(login_url='twitter:login')
def trainClass(request):
	print("======================NEW CLSS =======================")
	if request.method == 'POST':
		test_size = request.POST['newTest']
		random_state = request.POST['random_state']
		average = request.POST['average']
		obj = ClassifierSettings(test_size=test_size, rand_state=random_state, average=average)
		obj.save()
		source = {'test_size':obj.test_size, 'rand_state':obj.rand_state, 'average':obj.average}
		data = {'source': source}
		return JsonResponse(data)
		
@login_required(login_url='twitter:login')
def train_Model(request):
	print("======================NEW TRAIN=======================")
	data_two = {}
	if request.method == 'POST':
		print("<<<<<<<<<<<<<<<<<< 111")
		file = request.POST['sub_train']
		file_obj = analyticsUpload.objects.get(name=file)
		print("<<<<<<<<<<<<<<<<<< 1222")
		if ClassifierSettings.objects.all().count() != 0:
			settings = ClassifierSettings.objects.all().last()
			print("<<<<<<<<<<<<<<<<<< 333")
			classifier_model, scores, vectorizer = classifier.naive_bayes(file_obj.file, settings.test_size, settings.rand_state, settings.average)
			print("<<<<<<<<<<<<<<<<<< 444")
			data_scores = pd.DataFrame([scores])
			print("<<<<<<<<<<<<<<<<<< 5555")
			d = data_scores.to_json(orient='records')
			data = json.loads(d)

			allScore = []
			for score in data:
				allScore.append((score['correct'], score['incorrect'], score['accuracy'],
					score['recall'], score['precision'], score['f1_score']))

			correct = None
			incorrect = None
			accuracy = None
			recall = None
			precision = None
			f1_score = None

			for i in allScore:
				correct = str(i[0])
				incorrect = str(i[1])
				accuracy = str(i[2])
				recall = str(i[3])
				precision = str(i[4])
				f1_score = str(i[5])

				sourceTwo = {'correct':correct, 'incorrect':incorrect, 'accuracy':accuracy, 'recall':recall,
				'precision':precision, 'f1_score':f1_score}

				print("TRAINING COMPLETE")
				message = "TRAINING COMPLETE"
				data_two = {'sourceTwo':sourceTwo, 'message':message}
			

			entry = ClassifierModels(
				correct=correct, incorrect=incorrect, accuracy=accuracy,
				recall=recall, precision=precision, f1_score=f1_score)
			entry.save()

		print(type(data_two))		
		return JsonResponse(data_two)

# ========================================================================================
# DOWNLOAD TWEETS EXCEL
from twitter.backend import download_file as dl
def download_excel(request):
	request = dl.excel_dl(Tweets)
	return request
# ========================================================================================
# TWITTER MAIN TABLE 
from twitter.backend import tw_backend as tw
@login_required(login_url='twitter:login')
def twitter_data(request):
	api = tw.open_acct()
	num_post = 1
	# Admin Inputs
	if request.method == 'POST' and 'num_posts' in request.POST:
		num_post = int(request.POST.get('number'))

	if request.method == 'POST' and 'sour_sub' in request.POST:
		sources = SourceForm(request.POST)
		# obj = sources.source_acct
		if sources.is_valid():
			sources.save()
		else:
			print("Invalid")
	if Source.objects.all().count() == 0:
		accounts = []
	else:
		accounts = Source.objects.all()
		accounts = tw.output(accounts, api, num_post)		
	# CONTEXT
	tweets = Tweets.objects.all()
	context = {'tweets': tweets, 'source_list': accounts}
	return render(request, "twitter/analytics.html", context)
# ========================================================================================
# INTENTS MAIN TABLE
from twitter.backend import training_chatbot as train_bot
# from twitter.backend import intents_backend as intent 
@login_required(login_url='twitter:login')
def intents(request):
	json_file = "twitter/intents.json"
	with open (json_file, "r") as file:
		data = json.load(file)
	form = Intents.objects.all()

	try:
		form[0]
	except IndexError:
		for item in data["intents"]:
			Intents(
				tag= item["tag"], pattern= item["patterns"], response= item["responses"], 
				context= item["context"], context_set= item["context_set"]
				).save()

	# TRAINING OF CHATBOT MODEL 
	if request.method == 'POST' and 'train_chatbot' in request.POST:
		train_bot.chatbot_training(request, ChatbotTuning)

	
	elif request.method == 'POST':
		print('asdadadadadadada')	
		def convert(string):
			clean = []
			if len(string) == 0:
				return []
			li = re.split(r',(?=")', string)
			for word in li:
				chars = list(word)
				if len(chars)!= 0:
					chars.pop(0)
					chars.pop()
				word = "".join(chars)
				clean.append(word)
			return clean
		
		tag = request.POST.get('tag')
		patterns = convert(request.POST.get('patterns'))
		responses = convert(request.POST.get('responses'))
		context = request.POST.get('context')
		context_set = convert(request.POST.get('context_set'))

		print("++++++++++++==")		
		form = Intents(tag=tag, pattern=patterns, response=responses, context=context, context_set=context_set)
		form.save()
		new_obj = {"tag": tag, "patterns": patterns, "responses": responses, "context": context, "context_set": context_set}
		

		data["intents"].append(new_obj) 
		with open("twitter/intents.json", 'w') as data_file:
			json.dump(data, data_file, indent=4)
		return JsonResponse({'new_form': new_obj})

	tuner = ''
	if  ChatbotTuning.objects.all().count() != 0:
		tuner = ChatbotTuning.objects.last()
	
	dictionary = {'intents': form, 'tuner': tuner}
	# ====================================================================
	return render(request, "twitter/chatbot_intents.html", dictionary)

from twitter.backend import training_chatbot as train_bot
def tuningForm(request):
	print("======================TRAINING TUNING=======================")
	if request.method == 'POST':
		train_bot.chatbot_training(request, ChatbotTuning)
		epoch = request.POST['id_input_epoch']
		rate = request.POST['id_input_lr']
		batch = request.POST['id_input_bs']
		obj = ChatbotTuning(epoch=epoch, rate=rate, batch=batch)
		obj.save()
		source = {'epoch':obj.epoch, 'rate':obj.rate, 'batch':obj.batch}
		data = {'source': source}
		return JsonResponse(data)


class intentsDeleteView(View):
	def get(self,request, pk, *args, **kwargs):
		if request.is_ajax():
			print("<<<<<=================DELETE========================")
			tag = Intents.objects.get(pk=pk)
			tag_name = str(tag.tag)
			tag.delete()

twitter/templates/twitter/analytics.html
{% extends 'twitter/main_admin.html'%}
{% block title %}

Dashboard

{% endblock %}
{% block content %}

<div class="mcw">
  <!--navigation here-->
  <!--main content view-->
  <div class="cv">
    <div>
     <div class="inbox">

       <div class="inbox-bx container-fluid">
<div class="container">
{% if request.user.is_authenticated and request.user.is_staff %}
<h3>UE Twitter Data Analytics using Multinomial Naive Bayes Classification</h3>
	<section>
	<div class="add_source">
	
	
	<!-- ================================================================================= -->
	<!-- Number of Post to college input -->
	<div class="main_s">
<div class="main_s2">
	<div class="ma2">
	SOURCES(Data is multiplied by the number of sources):

	<section class="recentTwo">
		<!-- ------------------------ -->
		<div class="activity-card_two">
			<div class="table-responsive table_res">

		<table id="sourceTable" class="source_table">
			<thead>
				<tr>
					
					<th>Source Name</th>
					<th>Action</th>
				</tr>
				</thead>
				<tbody>
					{% for i in source_list %}
					<tr class="record">
						
						<td>{{i.source_acct}}</td>
						<td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="{% url 'twitter:source_delete' i.twitter_id %}" class="source_delete btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete"><span class="las la-trash-alt del_s"></span></a></p></td>
					</tr>
					{% endfor %}
				</tbody>
		</table>
	</div>
</div>
</section>

	<form method="POST" id="addUser">
		{% csrf_token %}
	    <div class="input-group mb-3">
			<div class="input-group-prepend">
				<span class="input-group-text" id="inputGroup-sizing-default">Add Source</span>
			</div>
			<input type="text" name="source_acct" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default">
			<button type="submit" class="btn btn-primary su" name="sour_sub">Submit</button>
			</div>
	    
	</form>
</div>
	<span class="ma1">
	<form method="POST">
		{% csrf_token %}
			<div class="input-group mb-3">
			<div class="input-group-prepend">
				<span class="input-group-text" id="inputGroup-sizing-default">Add Data #:</span>
			</div>
			<input type="text" name="number" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" onkeypress="isInputNumber(event)">
			<input type="submit" class="btn btn-primary su" name="num_posts">
			</div>
	    

	</form>
	</span>

	</div>

	<form method="POST" action="{% url 'twitter:download_excel' %}">
		{% csrf_token %}
		<button type="submit" value="Download EXCEL" name="download">
			Download_EXCEL
        	<span id="pdfButton2" ></span>                                    
        </button>

	</form>
</div>
	</div>
</section>

	<!-- ================================================================================== -->

	<section class="recent">
		<!-- ------------------------ -->
		<div class="activity-card">
			<div id="header-card">
				<h3>UE Official Twitter Page</h3>
			</div>

			<div class="table-responsive">
				<table id="myTable" class="table" >
				
					<thead>
						<tr>
							<th>#</th>
							<th>SOURCE</th>
							<th>POSTS</th>
							<th>LIKES</th>
							<th>DATE CREATED</th>
							<th>TIME CREATED</th>
							<th>HASHTAGS</th>
							<th>LINKS</th>
						</tr>
					</thead>
					<tbody>
						{% for i in tweets %}
						<tr>
							<td>{{forloop.counter}}</td>
							<td>{{i.source}}</td>
							<td>{{i.posts}}</td>
							<td>{{i.likes}}</td>
							<td>{{i.dates}}</td>
							<td>{{i.time}}</td>
							<td>{{i.tags}}</td>
							<td>{{i.links}}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>                  
	</section>
	<br>
	{% endif %}

	{% if request.user.is_authenticated and request.user and request.user.is_staff == False  %}
	<div class="not_authentic">
		<!-- <p>Sample user</p> -->
		<div class="cellcenterparent">
			<div class="cellcentercontent">
				<div class="message">
					<h3>You are not yet authorized to access this page !</h3>	
					<p>Come back later while we verify your account. Thank you!</p>	
				</div>
			</div>
		</div>
	
	</div>
		
	{% endif %} 
</div>

    </div>
     </div>
    </div>
  </div>
</div>


{% endblock content %}
{% block scripts %}

 {% for message in messages %}
    <script type="text/javascript">
      window.onload = function(){
        alert('{{message}}')
      }
    </script>
    {% endfor %}
    
<script type="text/javascript">


	$("form#addUser").submit(function() {
    var sourceInput = $('input[name="source_acct"]').val().trim();
    if (sourceInput) {
        // Create Ajax Call
        $.ajax({
            url: '{% url "twitter:crud_ajax_create" %}',
            data: {
                'source_acct': sourceInput,
            },
            dataType: 'json',
            success: function (data) {
                
                if (data.source) {
                  
                  appendToUsrTable(data.source);
                }
            }
        });
      } else {
        alert("Please check your input!.");
    }
    $('form#addUser').trigger("reset");
    return false;
});
	
function appendToUsrTable(source) {
	console.log(source.twitter_id)
	let sour = source.twitter_id;
	var url = "{% url 'twitter:source_delete' 123 %}".replace(/123/, sour.toString());

  $("#sourceTable > tbody:last-child").append(`
  	<tr class="record">
  	<td>${source.source_acct}</td>
  	<td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="${url}" class="source_delete2 btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete"><span class="las la-trash-alt del_s"></span></a></p></td>
  	<tr>
    `);

  $(".source_delete2").on("click", function(e){
    e.preventDefault();
    console.log("Hi")
    var $this = $(this);
    if(confirm("Sure to delete?")){
        $.ajax({
            url: $this.attr("href"),
            type: "GET",
            dataType: "json",
            success: function(resp){
                if(resp.message == "success"){
                    $this.parents(".record").fadeOut("slow", function(){
                        $this.parents(".record").remove();
                    });
                }else{
                    alert(resp.message);
                }
            }
        });
    }
    return false;
});
}

	$(".source_delete").on("click", function(e){
    e.preventDefault();
    console.log("Hi")
    var $this = $(this);
    if(confirm("Sure to delete?")){
        $.ajax({
            url: $this.attr("href"),
            type: "GET",
            dataType: "json",
            success: function(resp){
                if(resp.message == "success"){
                    $this.parents(".record").fadeOut("slow", function(){
                        $this.parents(".record").remove();
                    });
                }else{
                    alert(resp.message);
                }
            }
        });
    }
    return false;
});





</script>
{% endblock scripts %}

twitter/templates/twitter/base_try.html
{% load static %}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Title{% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% block stylesheet %}{% endblock stylesheet %}
  </head>
  <body>
    <main>
    {% block content %}
    {% endblock content %}
    </main>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
    <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>
    {% block javascript %}
    {% endblock javascript%}
  </body>
</html>

twitter/templates/twitter/links.html
{% extends 'twitter/main_admin.html'%}
{% block title %}

Links 

{% endblock %}
{% block content %}
<div class="mcw">
<div class="cv">
	<div>
		<div class="inbox">
			<div class="inbox-bx container-fluid">
				<div class="container"> 

					<div class="main_con2">
						<div class="links_head">
							<h2>Add UE Related Links</h2>
						</div>
						<form method="POST" id="addUserTwo">
							{% csrf_token %}
							<div class="form-row">
								<div class="form-group col-md-3">				
									<input type="text" name="link_name" class="form-control" placeholder="Link name" required>
								</div>
								<div class="form-group col-md-9">					
									<input type="text" name="links" class="form-control"  placeholder="Links URL" required>
								</div>
							</div>
							<div id="btn_links">
							<button type="submit" name="btn_links" class="btn btn-primary" >Add links</button>
							</div>
						</form>

			<section class="recentTwo">
                    <!-- ------------------------ -->
                    <div class="activity-card_two">
                        <div class="table-responsive table_res">
                            <table class="my_linkst" id="sourceTable">
                                <thead>
                                	<tr>
                                		<th>#</th>
                                		<th>Links Name</th>
                                		<th>Links URL</th>
                                		<th>Action</th>
                                	</tr>
                                </thead>
                                <tbody class="link_tb">
                                        {% for i in links %}
                                        <tr class="record">
                                        	<td class="count"></td>
                                        	<td>{{i.link_name}}</td>
                                        	<td>{{i.links}}</td>
                                        	<td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="{% url 'twitter:links_delete' i.link_id %}" class="source_delete btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete"><span class="las la-trash-alt del_s"></span></a></p></td>
                                        </tr>
                                        {% endfor %}
                                    
                                </tbody>
                            </table>

                        </div>
                    </div>    
            </section>

					</div>


				</div>
			</div>
		</div>
	</div>
</div>
</div>

<!-- ==================NOTES===================== -->
<!-- https://stackoverflow.com/questions/11026258/html-and-javascript-auto-increment-number -->


{% endblock content %}
{% block scripts %}
{% for message in messages %}
        <script type="text/javascript">
          window.onload = function(){
            alert('{{message}}')
          }
        </script>
{% endfor %}
<script type="text/javascript">
	 $(".link_tb").each(function(){
   $(this).html( $(this).html().replace(/((http|https|ftp):\/\/[\w?=&.\/-;#~%-]+(?![\w\s?&.\/;#~%"=-]*>))/g, '<a href="$1">$1</a> ') );
  });


$("form#addUserTwo").submit(function() {
    
    var links_name = $('input[name="link_name"]').val().trim();
    var links_tw = $('input[name="links"]').val().trim();
    if (links_name && links_tw) {
        // Create Ajax Call
        $.ajax({
            url: '{% url "twitter:linksViesUTwo" %}',
            data: {
                'link_name': links_name,
                'links': links_tw,
            },
            dataType: 'json',
            success: function (data) {
                
                if (data.source) {
                  
                  appendToUsrTable(data.source);
                }
            }
        });
      } else {
        alert("Please check your input!.");
    }
    $('form#addUserTwo').trigger("reset");
    return false;
});
	
function appendToUsrTable(source) {


	console.log(source.link_id)
	let sour = source.link_id;
	var url = "{% url 'twitter:links_delete' 123 %}".replace(/123/, sour.toString());

  $("#sourceTable > tbody:last-child").append(`
  	<tr class="record">
  	<td class="count"></td>
  	<td>${source.link_name}</td>
  	<td>${source.links}</td>
  	<td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="${url}" class="source_delete2 btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete"><span class="las la-trash-alt del_s"></span></a></p></td>
  	<tr>
    `);
  $(".record").each(function(){
		$(this).html( $(this).html().replace(/((http|https|ftp):\/\/[\w?=&.\/-;#~%-]+(?![\w\s?&.\/;#~%"=-]*>))/g, '<a href="$1">$1</a> ') );
	});

  $(".source_delete2").on("click", function(e){
    e.preventDefault();
    console.log("Hi")
    var $this = $(this);
    if(confirm("Sure to delete?")){
        $.ajax({
            url: $this.attr("href"),
            type: "GET",
            dataType: "json",
            success: function(resp){
                if(resp.message == "success"){
                    $this.parents(".record").fadeOut("slow", function(){
                        $this.parents(".record").remove();
                    });
                }else{
                    alert(resp.message);
                }
            }
        });
    }
    return false;
});
  


}



	 $(".source_delete").on("click", function(e){
	 	e.preventDefault();
	 	console.log("Hi")
	 	var $this = $(this);
	 	if(confirm("Sure to delete?")){
	 		$.ajax({
	 			url: $this.attr("href"),
	 			type: "GET",
	 			dataType: "json",
	 			success: function(resp){
	 				if(resp.message == "success"){
	 					$this.parents(".record").fadeOut("slow", function(){
	 						$this.parents(".record").remove();
	 					});
	 				}else{
	 					alert(resp.message);
	 				}
	 			}
	 		});
	 	}
	 	return false;
	 }); 
</script>
{% endblock scripts %}

twitter/templates/twitter/train.html
<!DOCTYPE html>
<html>
<head>
	<title>Training Data</title>
</head>
<body>
	<h1>Train Data</h1>
</body>
</html>

twitter/templates/twitter/train_classifier.html
<!DOCTYPE html>
<html>
<head>
	<title>Train Classifier</title>
</head>
<body>
	TRAINING COMPLETE 
</body>
</html>