chatbot/urls.py
from django.urls import path
from django.urls import reverse
from . import views
import twitter.views

app_name = 'chatbot'

urlpatterns = [
    path("chatbot/<uuid>/", views.chatbot, name='chatbot_chatbot'),
    path("post/<uuid>/", views.chatbot_process, name='post'),
    path("feed_create/", views.createFeedback, name='create'),
    path("lost_found_create/", views.lostFount, name='lost_found'),
    path("sample/", views.sample, name='sample'),
    path("", views.landing, name='home'),
    path("rule/", views.filter_acct, name='rule'),
    path("data_privacy/", views.data_privacy, name='data_privacy'),

]

twitter/urls.py
from django.urls import path
from . import views
from .views import (intentsDeleteView,sourcesDeleteView,linksDeleteView)
from django.conf import settings
from django.conf.urls.static import static

app_name = 'twitter'

urlpatterns = [
    path("dashboard/", views.twitter_data, name = "chatbot-twitter-data"),
    path("intents/", views.intents, name = "intents"),
    path("uedata/", views.uedata, name='uedata'),
    path("login/",views.accounts_login, name="login"),
    path('logout/', views.logout_view, name="logout"),

    path("intents/<int:pk>/", intentsDeleteView.as_view(), name="updata_delete"),
    path("twitter/<int:pk>/", sourcesDeleteView.as_view(), name="source_delete"),
    path("links/<int:pk>/", linksDeleteView.as_view(), name="links_delete"),


    path("side/", views.side, name="side"),

    
    path("Naive_bayes_Trainer/", views.upload, name="upload_file"),

    path("download_excel/", views.download_excel, name="download_excel"),
    

    path('crud/', views.CrudView.as_view(), name='crud_ajax'),
    path('ajax/crud/create/', views.CreateCrudUser.as_view(), name='crud_ajax_create'),

    path('links/', views.links, name="links"),
    path('ajax/crud/links/', views.linksViesUTwo.as_view(), name='linksViesUTwo'),
    path("classifier_create/", views.trainClass, name='classifier'),
    path("train_Model/", views.train_Model, name='train_model'),
    path("tuning_form/", views.tuningForm, name='tuning'),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter/forms.py
from django import forms
from django.forms import ModelForm
from twitter.models import *

from django.contrib.auth import authenticate
from django.contrib.auth import views
import os


from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.utils.translation import gettext_lazy as _

from django.core.exceptions import ValidationError

class ClassifierSettingsForm(ModelForm):
	class Meta:
		model = ClassifierSettings
		fields = ['average']

class linksForm(ModelForm):
	class Meta:
		model = linksModel
		fields = ['link_name', 'links']

class anaUploadForm(forms.FileField):
	filename = models.CharField(max_length=200)
	json_file = forms.FileField(widget=forms.FileInput(attrs={'accept':'application/pdf'}),)
	class Meta:
		model = analyticsUpload
		fields = '__all__'

class IntentsForm(ModelForm):
	class Meta:
		model = Intents
		fields = ["tag", "pattern", "response", "context", "context_set"]

class SourceForm(ModelForm):
	class Meta:
		model = Source
		fields = ['source_acct']


#ACCOUNT AUTHENTICATION
class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")

class RegistrationForm(UserCreationForm):
	email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')
	class Meta:
		model = Account
		fields = ('username', 'email', 'password1', 'password2',)

	def clean_email(self):

		email = self.cleaned_data['email'].lower()
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Exception as e:
			return email
		raise forms.ValidationError('Email "%s" is already in use.' % account)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except  Exception as e:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)

twitter/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
import pandas as pd
from django.contrib.auth.models import User
import os
import random
import json

from tensorflow.keras.models import load_model
# ============================================================
import subprocess
from .models import *
from .forms import *
import re
# ============================================================
from twitter.forms import SourceForm, RegistrationForm, AccountAuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password , check_password
from django.contrib import messages
from twitter.decorators import unauthenticated_user, allowed_users
# ============================================================
from django.views import View
from django.template import loader
# ============================================================
# from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import ListView

from django.core.files.storage import FileSystemStorage

# ========================================================================================

class CrudView(ListView):
    model = Source
    template_name = 'twitter/Crud.html'
    context_object_name = 'source'

class CreateCrudUser(View):
    def  get(self, request):
    	name_source = request.GET.get('source_acct', None)
    	print(name_source)
    	obj = Source.objects.create(source_acct = name_source)
    	source = {'twitter_id':obj.twitter_id,'source_acct':obj.source_acct}
    	data = {'source': source}
    	return JsonResponse(data)

class linksViesUTwo(View):
    def  get(self, request):
    	link_name = request.GET.get('link_name', None)
    	links = request.GET.get('links', None)
    	obj = linksModel.objects.create(link_name = link_name, links = links)
    	source = {'link_id':obj.link_id,'link_name':link_name, 'links':obj.links}
    	data = {'source': source}
    	return JsonResponse(data)
# ========================================================================================
# UPLOAD DATASET FOR NAIVE BAYES 
from twitter.backend import training_classifier as classifier
from twitter.backend import uploads 
@login_required(login_url='twitter:login')
def upload(request):
	files = analyticsUpload.objects.all()
	uploadsF = ClassifierSettingsForm()
	context = {
		'files': files,
		'classifier_settings': ClassifierSettings.objects.all().last(),
		'model_desc': ClassifierModels.objects.all().last(),
		'uploadsF':uploadsF
	}
	if request.method == 'POST' and 'upload_dataset' in request.POST:
		request = uploads.naive_bayes_upload(request, analyticsUpload)

	# if request.method == 'POST' and 'upload_class' in request.POST:
	# 	upload_classify = request.FILES['upload_input']
		# upload_file = FileSystemStorage() #GINAGAWA NYANG FileSystemStorage PAG NAG UPLOAD KA ULIT NG PAREHAS NA FILE NAME PAPALITAN NYA YUN NG BAGONG FILE NAME
		# upload_file.save(upload_classify.name, upload_classify)
	
	
	# if request.method == 'POST' and 'upload_toClassify' in request.POST:
	# 	# TAKE NOTE: FIND A WAY TO SAVE AN INSTANCE OF A CLASS
	# 	pass

	return render(request, "twitter/upload_file/analytics_upload.html", context)

@login_required(login_url='twitter:login')
def trainClass(request):
	print("======================NEW CLSS =======================")
	if request.method == 'POST':
		test_size = request.POST['newTest']
		random_state = request.POST['random_state']
		average = request.POST['average']
		obj = ClassifierSettings(test_size=test_size, rand_state=random_state, average=average)
		obj.save()
		source = {'test_size':obj.test_size, 'rand_state':obj.rand_state, 'average':obj.average}
		data = {'source': source}
		return JsonResponse(data)
		
@login_required(login_url='twitter:login')
def train_Model(request):
	print("======================NEW TRAIN=======================")
	data_two = {}
	if request.method == 'POST':
		print("<<<<<<<<<<<<<<<<<< 111")
		file = request.POST['sub_train']
		file_obj = analyticsUpload.objects.get(name=file)
		print("<<<<<<<<<<<<<<<<<< 1222")
		if ClassifierSettings.objects.all().count() != 0:
			settings = ClassifierSettings.objects.all().last()
			print("<<<<<<<<<<<<<<<<<< 333")
			classifier_model, scores, vectorizer = classifier.naive_bayes(file_obj.file, settings.test_size, settings.rand_state, settings.average)
			print("<<<<<<<<<<<<<<<<<< 444")
			data_scores = pd.DataFrame([scores])
			print("<<<<<<<<<<<<<<<<<< 5555")
			d = data_scores.to_json(orient='records')
			data = json.loads(d)

			allScore = []
			for score in data:
				allScore.append((score['correct'], score['incorrect'], score['accuracy'],
					score['recall'], score['precision'], score['f1_score']))

			correct = None
			incorrect = None
			accuracy = None
			recall = None
			precision = None
			f1_score = None

			for i in allScore:
				correct = str(i[0])
				incorrect = str(i[1])
				accuracy = str(i[2])
				recall = str(i[3])
				precision = str(i[4])
				f1_score = str(i[5])

				sourceTwo = {'correct':correct, 'incorrect':incorrect, 'accuracy':accuracy, 'recall':recall,
				'precision':precision, 'f1_score':f1_score}

				print("TRAINING COMPLETE")
				message = "TRAINING COMPLETE"
				data_two = {'sourceTwo':sourceTwo, 'message':message}
			

			entry = ClassifierModels(
				correct=correct, incorrect=incorrect, accuracy=accuracy,
				recall=recall, precision=precision, f1_score=f1_score)
			entry.save()

		print(type(data_two))		
		return JsonResponse(data_two)

# ========================================================================================
# DOWNLOAD TWEETS EXCEL
from twitter.backend import download_file as dl
def download_excel(request):
	request = dl.excel_dl(Tweets)
	return request
# ========================================================================================
# TWITTER MAIN TABLE 
from twitter.backend import tw_backend as tw
@login_required(login_url='twitter:login')
def twitter_data(request):
	api = tw.open_acct()
	num_post = 1
	# Admin Inputs
	if request.method == 'POST' and 'num_posts' in request.POST:
		num_post = int(request.POST.get('number'))

	if request.method == 'POST' and 'sour_sub' in request.POST:
		sources = SourceForm(request.POST)
		# obj = sources.source_acct
		if sources.is_valid():
			sources.save()
		else:
			print("Invalid")
	if Source.objects.all().count() == 0:
		accounts = []
	else:
		accounts = Source.objects.all()
		accounts = tw.output(accounts, api, num_post)		
	# CONTEXT
	tweets = Tweets.objects.all()
	context = {'tweets': tweets, 'source_list': accounts}
	return render(request, "twitter/analytics.html", context)
# ========================================================================================
# INTENTS MAIN TABLE
from twitter.backend import training_chatbot as train_bot
# from twitter.backend import intents_backend as intent 
@login_required(login_url='twitter:login')
def intents(request):
	json_file = "twitter/intents.json"
	with open (json_file, "r") as file:
		data = json.load(file)
	form = Intents.objects.all()

	try:
		form[0]
	except IndexError:
		for item in data["intents"]:
			Intents(
				tag= item["tag"], pattern= item["patterns"], response= item["responses"], 
				context= item["context"], context_set= item["context_set"]
				).save()

	# TRAINING OF CHATBOT MODEL 
	if request.method == 'POST' and 'train_chatbot' in request.POST:
		train_bot.chatbot_training(request, ChatbotTuning)

	
	elif request.method == 'POST':
		print('asdadadadadadada')	
		def convert(string):
			clean = []
			if len(string) == 0:
				return []
			li = re.split(r',(?=")', string)
			for word in li:
				chars = list(word)
				if len(chars)!= 0:
					chars.pop(0)
					chars.pop()
				word = "".join(chars)
				clean.append(word)
			return clean
		
		tag = request.POST.get('tag')
		patterns = convert(request.POST.get('patterns'))
		responses = convert(request.POST.get('responses'))
		context = request.POST.get('context')
		context_set = convert(request.POST.get('context_set'))

		print("++++++++++++==")		
		form = Intents(tag=tag, pattern=patterns, response=responses, context=context, context_set=context_set)
		form.save()
		new_obj = {"tag": tag, "patterns": patterns, "responses": responses, "context": context, "context_set": context_set}
		

		data["intents"].append(new_obj) 
		with open("twitter/intents.json", 'w') as data_file:
			json.dump(data, data_file, indent=4)
		return JsonResponse({'new_form': new_obj})

	tuner = ''
	if  ChatbotTuning.objects.all().count() != 0:
		tuner = ChatbotTuning.objects.last()
	
	dictionary = {'intents': form, 'tuner': tuner}
	# ====================================================================
	return render(request, "twitter/chatbot_intents.html", dictionary)

from twitter.backend import training_chatbot as train_bot
def tuningForm(request):
	print("======================TRAINING TUNING=======================")
	if request.method == 'POST':
		train_bot.chatbot_training(request, ChatbotTuning)
		epoch = request.POST['id_input_epoch']
		rate = request.POST['id_input_lr']
		batch = request.POST['id_input_bs']
		obj = ChatbotTuning(epoch=epoch, rate=rate, batch=batch)
		obj.save()
		source = {'epoch':obj.epoch, 'rate':obj.rate, 'batch':obj.batch}
		data = {'source': source}
		return JsonResponse(data)


class intentsDeleteView(View):
	def get(self,request, pk, *args, **kwargs):
		if request.is_ajax():
			print("<<<<<=================DELETE========================")
			tag = Intents.objects.get(pk=pk)
			tag_name = str(tag.tag)
			tag.delete()

twitter/templates/twitter/upload_file/analytics_upload.html
{% extends 'twitter/main_admin.html'%}
{% block title %}

Upload file 

{% endblock %}
{% block content %}

<div class="mcw">
  <!--navigation here-->
  <!--main content view-->
  <div class="cv">
    <div>
     <div class="inbox">

       <div class="inbox-bx container-fluid">
<div class="container">
<div class="Up_flex">
 <div class="main_upload">

 <div class="main">

  <form method="POST" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
      <h3>Upload Files</h3>

<!-- https://codepen.io/sazzad/pen/antDJ -->

 <div class="file-upload1">
    	<div class="file-select">
    		<div class="file-select-button" id="fileName2">Choose File</div>
    		<div class="file-select-name" id="noFile2">No file chosen...</div> 
    		<input type="file" id="upload_data" name="file">
    	</div>
    </div>

     <button type="submit" name="upload_dataset" class="btn btn-primary upload_dataset">Upload file</button>
     
  </form>
 </div>

<div class="view_settings">
	<div class="trai_set">
		<h3>Training Settings</h3>
		<p>Test Size: <span id="test_size"> </span></p>
		<p>Random State: <span id="state"> </span></p>
		<p>Average option: <span id="aver"> </span></p><br>
	</div>

	<div class="class_des">
		<!-- If not exist, print(None trained classifier model) -->
		<h3>Classifier Description</h3>
		<p>Number of Correct: <span id="class_correct"></span></p>
		<p>Number of Incorrect: <span id="class_incorrect"></span></p>
		<p>Accuracy: <span id="class_accuracy"></span></p>
		<p>Recall Score: <span id="class_recall"></span></p>
		<p>Precision Score: <span id="class_precision"></span></p>
		<p class="f1">F1 Score: <span id="class_f1"></span></p><br>
	</div>
</div>

<div class="classfier_inputs">
	<form method="POST" id="classForm">
		{% csrf_token %}
		<h3>Set Training Parameters</h3>

			<!-- Test size = decimal from 0-1, example: 0.30(default) -->
		<!-- Random state = integer from 1-100, example: 88 (default)-->
		<!-- Average = (None, 'micro', 'macro'(default), 'weighted', 'samples') -->

			<div class="form-group">
				<label for="newTest">Test size(decimal):</label>
				<input type="text" id="newTest" placeholder="0-1" onkeypress="return isNumberKey(event,this.id)" class="form-control" name="test_size" required>
			</div>

			<div class="form-group">
				<label for="random_state">Random State:</label>
				<input type="text" placeholder="1-100" id="random_state" maxlength="3" onkeypress="isInputNumber(event)" class="form-control" name="random_state" required>
			</div>

			<div class="form-group select_css">
				<label for="inputState">Average</label>
				<select id="average"  class="form-control" name="average" style="cursor:pointer;" required>
					<{% for value, upload in uploadsF.fields.average.choices %}
					<option value="{{value}}">{{upload}}</option>
					{% endfor %}
				</select>
			</div>

		<button type="submit"name="new_settings" class="btn btn-primary">Submit</button>
	</form>

</div>


<!--   <form method="POST" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
      <h3>Classify Excel</h3> -->

<!-- https://codepen.io/sazzad/pen/antDJ -->
<!--     <div class="file-upload">
    	<div class="file-select">
    		<div class="file-select-button" id="fileName">Choose File</div>
    		<div class="file-select-name" id="noFile">No file chosen...</div> 
    		<input type="file" name="upload_input" id="chooseFile">
    	</div>
    </div>

     <button type="submit" name="upload_class" class="btn btn-primary upload_dataset">Classify</button>
     
  </form> -->

<div class="file_table">
		<section class="recentTwo">
                    <!-- ------------------------ -->
                    <div class="activity-card_two">
                        <div class="table-responsive table_res">
	<table class="file_main_table">				
		<thead>
			<tr>
				<th>NUMBER</th>
				<th>FILE NAME</th>
				<th>FILE EXTENSION</th>
				<th>FILE PATH</th>
				<th>TRAIN AS MODEL</th>
			</tr>
		</thead>
		<tbody>
			{% for i in files %}
			<tr>
				<td>{{forloop.counter}}</td>
				<td>{{i.name}}</td>
				<td>{{i.file_type}}</td>
				<td>{{i.file}}</td>
				<td>
					<form method="POST" id="train_Model">
						{% csrf_token %}
						<input type="submit" id="sub_train" class="btn btn-success" name="train_model" value="{{i.name}}">
					</form>
				</td>
				
			</tr>
			{% endfor %}
		</tbody>
	</table>
	</div>
</div>
</section>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>


{% endblock %}

{% block scripts %}

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.2/dist/sweetalert2.all.min.js"></script>
{% for message in messages %}
    <script type="text/javascript">
      window.onload = function(){
        Swal.fire({
        	icon: 'error',
        	title: 'Please check your file! ',
        	text: '{{message}}',
        })
      }
    </script>
{% endfor %}

<script type="text/javascript" src="//code.jquery.com/jquery-1.10.2.min.js"></script>
<script type="text/javascript">



$('#upload_form').on("click", ":submit", function (e) {

  if (!$('#upload_data').val()) {
  e.preventDefault();
  Swal.fire({
  	icon: 'info',
  	title: 'Please upload a file! ',

})
  }

});

  function isInputNumber(evt){
                
    var ch = String.fromCharCode(evt.which);
                
    if(!(/[0-9]/.test(ch))){
      evt.preventDefault();
    }             
}

function isNumberKey(evt,id)
{
	try{
        var charCode = (evt.which) ? evt.which : event.keyCode;
  
        if(charCode==46){
            var txt=document.getElementById(id).value;
            if(!(txt.indexOf(".") > -1)){
	
                return true;
            }
        }
        if (charCode > 31 && (charCode < 48 || charCode > 57) )
            return false;

        return true;
	}catch(w){
		alert(w);
	}
}

// $('#upload_form').submit(function(event){
//     validated = true;

//     if ($('#upload_data').get(0).files.length === 0) {
//         validated = false;
//         console.log("No files selected.");
//         // Or some div with image showing
//     }

//     if (validated != true) {
//         event.preventDefault();
//     }
// });

$('#chooseFile').bind('change', function () {
  var filename = $("#chooseFile").val();
  if (/^\s*$/.test(filename)) {
    $(".file-upload").removeClass('active');
    $("#noFile").text("No file chosen..."); 
  }
  else {
    $(".file-upload").addClass('active');
    $("#noFile").text(filename.replace("C:\\fakepath\\", "")); 
  }
});


	$('#upload_data').bind('change', function () {
  var filename = $("#upload_data").val();
  if (/^\s*$/.test(filename)) {
    $(".file-upload1").removeClass('active');
    $("#noFile2").text("No file chosen..."); 
  }
  else {
    $(".file-upload1").addClass('active');
    $("#noFile2").text(filename.replace("C:\\fakepath\\", "")); 
  }
});


	$("#classForm").on("submit", function(e){
	e.preventDefault();
		var url = '{% url "twitter:classifier" %}'
		var random = document.getElementById("random_state").value;
		var convert = parseInt(random);

		if(convert > 100){
			e.preventDefault();
				Swal.fire({
					position: 'center',
					icon: 'error',
					title: 'Please check your input! at Random State ',
					text: 'Max number is 100!',
					showConfirmButton: false,
					timer: 1900
				})

		}else{
		$.ajax({
			type:'POST',
			url:url,
			data:{
				newTest:$('#newTest').val(),
				random_state:$('#random_state').val(),
				average:$('#average').val(),
				csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
			},
			dataType: 'json',
			success:function(data){
				Swal.fire({
					position: 'center',
					icon: 'success',
					title: 'Successfully Save!',
					showConfirmButton: false,
					timer: 1600
				})
				var size_test = data.source.test_size;
				var rand_state = data.source.rand_state;
				var average = data.source.average;

				document.getElementById("test_size").innerHTML = size_test;
				document.getElementById("state").innerHTML = rand_state;
				document.getElementById("aver").innerHTML = average;


				$('#newTest').val('');
				$('#random_state').val('');
				$('#average').val('');
			}
			
		});
		}
	});


	$("#train_Model").on("submit", function(e){
		e.preventDefault();
		console.log('TRAAAAIN')
		var url = '{% url "twitter:train_model" %}'
		$.ajax({
			type:'POST',
			url:url,
			data:{
				sub_train:$('#sub_train').val(),
				csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
			},
			dataType: 'json',
			success:function(data_two){
				Swal.fire({
					position: 'center',
					icon: 'success',
					title: data_two.message,
					showConfirmButton: false,
					timer: 1600
				})

				var correct = data_two.sourceTwo.correct;
				var incorrect = data_two.sourceTwo.incorrect;
				var accuracy = data_two.sourceTwo.accuracy;
				var recall = data_two.sourceTwo.recall;
				var precision = data_two.sourceTwo.precision;
				var f1_score = data_two.sourceTwo.f1_score;

				document.getElementById("class_correct").innerHTML = correct;
				document.getElementById("class_incorrect").innerHTML = incorrect;
				document.getElementById("class_accuracy").innerHTML = accuracy;
				document.getElementById("class_recall").innerHTML = recall;
				document.getElementById("class_precision").innerHTML = precision;
				document.getElementById("class_f1").innerHTML = f1_score;

				
			

			}
			
		});
	});


</script>
{% endblock scripts %}